package com.webmapping.backend.config;

import com.webmapping.backend.model.Categorie;
import com.webmapping.backend.model.Etablissement;
import com.webmapping.backend.model.Quartier;
import com.webmapping.backend.repository.CategorieRepository;
import com.webmapping.backend.repository.EtablissementRepository;
import com.webmapping.backend.repository.QuartierRepository;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.GeometryFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.math.BigDecimal;
import java.util.Arrays;

@Configuration
public class DataSeeder {

    @Bean
    CommandLineRunner initDatabase(CategorieRepository categorieRepository,
                                   QuartierRepository quartierRepository,
                                   EtablissementRepository etablissementRepository) {
        return args -> {
            if (categorieRepository.count() == 0) {
                Categorie hotel = new Categorie(null, "hotel");
                Categorie restaurant = new Categorie(null, "restaurant");
                categorieRepository.save(hotel);
                categorieRepository.save(restaurant);

                GeometryFactory geometryFactory = new GeometryFactory();

                Etablissement e0 = new Etablissement();
                e0.setNom("Ikopa Hôtel Madagascar - Resort and Spa");
                e0.setAdresse("Akadindratombo");
                e0.setTelephone("+261 34 36 868 88");
                e0.setPrixMoyen(new BigDecimal("130500"));
                e0.setNote(new BigDecimal("3"));
                e0.setPhotos(Arrays.asList("ikopa1.jpg", "ikopa2.jpg", "ikopa3.jpg", "ikopa4.jpg", "ikopa5.jpg", "ikopa6.jpg", "ikopa7.jpg", "ikopa8.jpg", "ikopa-hotel-madagascar.jpg"));
                e0.setDescription("Bienvenue à Ikopa Hôtel Madagascar - Resort and Spa. Situé dans le quartier de Akadindratombo.");
                e0.setCategorie(hotel);
                e0.setGeom(geometryFactory.createPoint(new Coordinate(47.559924, -18.934280)));
                e0.getGeom().setSRID(4326);
                etablissementRepository.save(e0);

                Etablissement e1 = new Etablissement();
                e1.setNom("Radisson Blu Hotel Antananarivo Waterfront");
                e1.setAdresse("Tana Waterfront");
                e1.setTelephone("+261 20 22 692 00");
                e1.setPrixMoyen(new BigDecimal("756000"));
                e1.setNote(new BigDecimal("5"));
                e1.setPhotos(Arrays.asList("radisson1.jpg", "radisson2.jpg", "radisson3.jpg"));
                e1.setDescription("Bienvenue à Radisson Blu Hotel Antananarivo Waterfront. Situé dans le quartier de Tana Waterfront.");
                e1.setCategorie(hotel);
                e1.setGeom(geometryFactory.createPoint(new Coordinate(47.524666, -18.890256)));
                e1.getGeom().setSRID(4326);
                etablissementRepository.save(e1);

                Etablissement e2 = new Etablissement();
                e2.setNom("Hôtel Carlton");
                e2.setAdresse("Anosy");
                e2.setTelephone("+261 20 22 260 60");
                e2.setPrixMoyen(new BigDecimal("607500"));
                e2.setNote(new BigDecimal("5"));
                e2.setPhotos(Arrays.asList("carlton1.jpg", "carlton2.jpg", "carlton3.jpg", "carlton4.jpg"));
                e2.setDescription("Bienvenue à Hôtel Carlton. Situé dans le quartier de Anosy.");
                e2.setCategorie(hotel);
                e2.setGeom(geometryFactory.createPoint(new Coordinate(47.517849, -18.914848)));
                e2.getGeom().setSRID(4326);
                etablissementRepository.save(e2);

                Etablissement e3 = new Etablissement();
                e3.setNom("FLY INN Madagascar Hôtel");
                e3.setAdresse("Ivato (Aéroport)");
                e3.setTelephone("+261 33 73 594 66");
                e3.setPrixMoyen(new BigDecimal("324000"));
                e3.setNote(new BigDecimal("3"));
                e3.setPhotos(Arrays.asList("fly1.jpg", "fly2.jpg"));
                e3.setDescription("Bienvenue à FLY INN Madagascar Hôtel. Situé dans le quartier de Ivato (Aéroport).");
                e3.setCategorie(hotel);
                e3.setGeom(geometryFactory.createPoint(new Coordinate(47.472738, -18.802978)));
                e3.getGeom().setSRID(4326);
                etablissementRepository.save(e3);

                Etablissement e4 = new Etablissement();
                e4.setNom("Madagascar Underground");
                e4.setAdresse("Antananarivo Centre");
                e4.setTelephone("+261 38 99 503 32");
                e4.setPrixMoyen(new BigDecimal("90000"));
                e4.setNote(new BigDecimal("3"));
                e4.setPhotos(Arrays.asList("underground1.jpg", "underground2.jpg"));
                e4.setDescription("Bienvenue à Madagascar Underground. Situé dans le quartier de Antananarivo Centre.");
                e4.setCategorie(hotel);
                e4.setGeom(geometryFactory.createPoint(new Coordinate(47.523467, -18.909928)));
                e4.getGeom().setSRID(4326);
                etablissementRepository.save(e4);

                Etablissement e5 = new Etablissement();
                e5.setNom("Maison d'Hôtes Mandrosoa");
                e5.setAdresse("Ambohijatovo");
                e5.setTelephone("+261 34 75 974 73");
                e5.setPrixMoyen(new BigDecimal("130500"));
                e5.setNote(new BigDecimal("3"));
                e5.setPhotos(Arrays.asList("mandrosoa1.jpg"));
                e5.setDescription("Bienvenue à Maison d'Hôtes Mandrosoa. Situé dans le quartier de Ambohijatovo.");
                e5.setCategorie(hotel);
                e5.setGeom(geometryFactory.createPoint(new Coordinate(47.528798, -18.910407)));
                e5.getGeom().setSRID(4326);
                etablissementRepository.save(e5);

                Etablissement e6 = new Etablissement();
                e6.setNom("Central Hotel Tana");
                e6.setAdresse("Tsaralalana");
                e6.setTelephone("+261 20 22 222 44");
                e6.setPrixMoyen(new BigDecimal("207000"));
                e6.setNote(new BigDecimal("3"));
                e6.setPhotos(Arrays.asList("central1.jpg", "central2.jpg"));
                e6.setDescription("Bienvenue à Central Hotel Tana. Situé dans le quartier de Tsaralalana.");
                e6.setCategorie(hotel);
                e6.setGeom(geometryFactory.createPoint(new Coordinate(47.520710, -18.906780)));
                e6.getGeom().setSRID(4326);
                etablissementRepository.save(e6);

                Etablissement e7 = new Etablissement();
                e7.setNom("Sakamanga Hôtel");
                e7.setAdresse("Ampasamadinika");
                e7.setTelephone("+261 32 02 668 34");
                e7.setPrixMoyen(new BigDecimal("346500"));
                e7.setNote(new BigDecimal("3"));
                e7.setPhotos(Arrays.asList("sakamanga1.jpg", "sakamanga2.jpg"));
                e7.setDescription("Bienvenue à Sakamanga Hôtel. Situé dans le quartier de Ampasamadinika.");
                e7.setCategorie(hotel);
                e7.setGeom(geometryFactory.createPoint(new Coordinate(47.521248, -18.908370)));
                e7.getGeom().setSRID(4326);
                etablissementRepository.save(e7);

                Etablissement e8 = new Etablissement();
                e8.setNom("Sole Hotel");
                e8.setAdresse("Antananarivo Centre");
                e8.setTelephone("+261 38 49 066 06");
                e8.setPrixMoyen(new BigDecimal("157500"));
                e8.setNote(new BigDecimal("2"));
                e8.setPhotos(Arrays.asList("sole1.jpg"));
                e8.setDescription("Bienvenue à Sole Hotel. Situé dans le quartier de Antananarivo Centre.");
                e8.setCategorie(hotel);
                e8.setGeom(geometryFactory.createPoint(new Coordinate(47.522007, -18.907016)));
                e8.getGeom().setSRID(4326);
                etablissementRepository.save(e8);

                Etablissement e9 = new Etablissement();
                e9.setNom("Feima Hotel Analakely");
                e9.setAdresse("Analakely");
                e9.setTelephone("+261 33 61 999 99");
                e9.setPrixMoyen(new BigDecimal("553500"));
                e9.setNote(new BigDecimal("3"));
                e9.setPhotos(Arrays.asList("feima.jpg", "feima2.jpg"));
                e9.setDescription("Bienvenue à Feima Hotel Analakely. Situé dans le quartier de Analakely.");
                e9.setCategorie(hotel);
                e9.setGeom(geometryFactory.createPoint(new Coordinate(47.524478, -18.906062)));
                e9.getGeom().setSRID(4326);
                etablissementRepository.save(e9);

                Etablissement e10 = new Etablissement();
                e10.setNom("Hôtel Bel'Air Antananarivo");
                e10.setAdresse("Analamahitsy");
                e10.setTelephone("+261 34 78 513 78");
                e10.setPrixMoyen(new BigDecimal("112500"));
                e10.setNote(new BigDecimal("3"));
                e10.setPhotos(Arrays.asList("belair.jpeg", "belair2.jpeg"));
                e10.setDescription("Bienvenue à Hôtel Bel'Air Antananarivo. Situé dans le quartier de Analamahitsy.");
                e10.setCategorie(hotel);
                e10.setGeom(geometryFactory.createPoint(new Coordinate(47.542716, -18.872211)));
                e10.getGeom().setSRID(4326);
                etablissementRepository.save(e10);

                Etablissement e11 = new Etablissement();
                e11.setNom("Palm Hôtel Antananarivo");
                e11.setAdresse("Lalana Andrianary Ratianarivo");
                e11.setTelephone("+261 32 05 536 80");
                e11.setPrixMoyen(new BigDecimal("144000"));
                e11.setNote(new BigDecimal("2"));
                e11.setPhotos(Arrays.asList("palm1.jpg", "palm2.jpg", "palm3.jpg"));
                e11.setDescription("Bienvenue à Palm Hôtel Antananarivo. Situé dans le quartier de Lalana Andrianary Ratianarivo.");
                e11.setCategorie(hotel);
                e11.setGeom(geometryFactory.createPoint(new Coordinate(47.522141, -18.907887)));
                e11.getGeom().setSRID(4326);
                etablissementRepository.save(e11);

                Etablissement e12 = new Etablissement();
                e12.setNom("Hôtel Brajas");
                e12.setAdresse("Ambondrona");
                e12.setTelephone("+261 34 07 263 35");
                e12.setPrixMoyen(new BigDecimal("121500"));
                e12.setNote(new BigDecimal("2"));
                e12.setPhotos(Arrays.asList("brajas1.jpg", "brajas2.jpg"));
                e12.setDescription("Bienvenue à Hôtel Brajas. Situé dans le quartier de Ambondrona.");
                e12.setCategorie(hotel);
                e12.setGeom(geometryFactory.createPoint(new Coordinate(47.527909, -18.906351)));
                e12.getGeom().setSRID(4326);
                etablissementRepository.save(e12);

                Etablissement e13 = new Etablissement();
                e13.setNom("Hotel Cristal Madagascar");
                e13.setAdresse("Behoririka");
                e13.setTelephone("+261 34 05 670 58");
                e13.setPrixMoyen(new BigDecimal("94500"));
                e13.setNote(new BigDecimal("3"));
                e13.setPhotos(Arrays.asList("cristal1.jpg"));
                e13.setDescription("Bienvenue à Hotel Cristal Madagascar. Situé dans le quartier de Behoririka.");
                e13.setCategorie(hotel);
                e13.setGeom(geometryFactory.createPoint(new Coordinate(47.526785, -18.902415)));
                e13.getGeom().setSRID(4326);
                etablissementRepository.save(e13);

                Etablissement e14 = new Etablissement();
                e14.setNom("Hôtel Atmosphère & Spa");
                e14.setAdresse("Ankorondrano");
                e14.setTelephone("+261 38 48 859 15");
                e14.setPrixMoyen(new BigDecimal("225000"));
                e14.setNote(new BigDecimal("3"));
                e14.setPhotos(Arrays.asList("atmosphere1.jpg", "atmosphere2.jpg", "atmosphere3.jpg", "atmosphere4.jpg"));
                e14.setDescription("Bienvenue à Hôtel Atmosphère & Spa. Situé dans le quartier de Ankorondrano.");
                e14.setCategorie(hotel);
                e14.setGeom(geometryFactory.createPoint(new Coordinate(47.522049, -18.886102)));
                e14.getGeom().setSRID(4326);
                etablissementRepository.save(e14);

                Etablissement e15 = new Etablissement();
                e15.setNom("Valiha Hotel Antananarivo Antanimena");
                e15.setAdresse("Antanimena");
                e15.setTelephone("+261 38 78 000 77");
                e15.setPrixMoyen(new BigDecimal("162000"));
                e15.setNote(new BigDecimal("3"));
                e15.setPhotos(Arrays.asList("valiha1.jpg", "valiha2.jpg", "valiha3.jpg", "valiha4.jpg"));
                e15.setDescription("Bienvenue à Valiha Hotel Antananarivo Antanimena. Situé dans le quartier de Antanimena.");
                e15.setCategorie(hotel);
                e15.setGeom(geometryFactory.createPoint(new Coordinate(47.521015, -18.897891)));
                e15.getGeom().setSRID(4326);
                etablissementRepository.save(e15);

                Etablissement e16 = new Etablissement();
                e16.setNom("Tsanga Tsanga Hôtel");
                e16.setAdresse("Tsaralalana");
                e16.setTelephone("+261 34 77 703 61");
                e16.setPrixMoyen(new BigDecimal("270000"));
                e16.setNote(new BigDecimal("3"));
                e16.setPhotos(Arrays.asList("tsanga1.jpg", "tsanga2.jpg"));
                e16.setDescription("Bienvenue à Tsanga Tsanga Hôtel. Situé dans le quartier de Tsaralalana.");
                e16.setCategorie(hotel);
                e16.setGeom(geometryFactory.createPoint(new Coordinate(47.521714, -18.906629)));
                e16.getGeom().setSRID(4326);
                etablissementRepository.save(e16);

                Etablissement e17 = new Etablissement();
                e17.setNom("Sunny Garden Hotel");
                e17.setAdresse("Ankorondrano");
                e17.setTelephone("+261 33 11 323 85");
                e17.setPrixMoyen(new BigDecimal("292500"));
                e17.setNote(new BigDecimal("4"));
                e17.setPhotos(Arrays.asList("sunny1.jpg", "sunny2.jpg", "sunny3.jpg"));
                e17.setDescription("Bienvenue à Sunny Garden Hotel. Situé dans le quartier de Ankorondrano.");
                e17.setCategorie(hotel);
                e17.setGeom(geometryFactory.createPoint(new Coordinate(47.522667, -18.886337)));
                e17.getGeom().setSRID(4326);
                etablissementRepository.save(e17);

                Etablissement e18 = new Etablissement();
                e18.setNom("Zara Hôtel");
                e18.setAdresse("Ankasina");
                e18.setTelephone("+261 32 07 088 88");
                e18.setPrixMoyen(new BigDecimal("175500"));
                e18.setNote(new BigDecimal("3"));
                e18.setPhotos(Arrays.asList("zara1.jpg", "zara2.jpg"));
                e18.setDescription("Bienvenue à Zara Hôtel. Situé dans le quartier de Ankasina.");
                e18.setCategorie(hotel);
                e18.setGeom(geometryFactory.createPoint(new Coordinate(47.510234, -18.897255)));
                e18.getGeom().setSRID(4326);
                etablissementRepository.save(e18);

                Etablissement e19 = new Etablissement();
                e19.setNom("San Cristobal Boutique Hotel");
                e19.setAdresse("Ivato Aéroport");
                e19.setTelephone("+261 34 05 024 91");
                e19.setPrixMoyen(new BigDecimal("279000"));
                e19.setNote(new BigDecimal("3"));
                e19.setPhotos(Arrays.asList("sancristobal.jpg", "sancristobal2.jpg", "sancristobal3.jpg"));
                e19.setDescription("Bienvenue à San Cristobal Boutique Hotel. Situé dans le quartier de Ivato Aéroport.");
                e19.setCategorie(hotel);
                e19.setGeom(geometryFactory.createPoint(new Coordinate(47.464219, -18.830554)));
                e19.getGeom().setSRID(4326);
                etablissementRepository.save(e19);

                Etablissement e20 = new Etablissement();
                e20.setNom("Les Flots Bleu");
                e20.setAdresse("Antehiroka");
                e20.setTelephone("+261 34 19 401 42");
                e20.setPrixMoyen(new BigDecimal("103500"));
                e20.setNote(new BigDecimal("2"));
                e20.setPhotos(Arrays.asList("flotsbleu1.jpg", "flotsbleu2.jpg", "flotsbleu3.jpg", "flotsbleu4.jpg"));
                e20.setDescription("Bienvenue à Les Flots Bleu. Situé dans le quartier de Antehiroka.");
                e20.setCategorie(hotel);
                e20.setGeom(geometryFactory.createPoint(new Coordinate(47.467301, -18.853161)));
                e20.getGeom().setSRID(4326);
                etablissementRepository.save(e20);

                Etablissement e21 = new Etablissement();
                e21.setNom("NY Telomiova");
                e21.setAdresse("Talatamaty");
                e21.setTelephone("+261 33 63 348 39");
                e21.setPrixMoyen(new BigDecimal("72000"));
                e21.setNote(new BigDecimal("3"));
                e21.setPhotos(Arrays.asList("telomiova.jpg", "telomiova2.jpg", "telomiova3.jpg"));
                e21.setDescription("Bienvenue à NY Telomiova. Situé dans le quartier de Talatamaty.");
                e21.setCategorie(hotel);
                e21.setGeom(geometryFactory.createPoint(new Coordinate(47.468670, -18.842498)));
                e21.getGeom().setSRID(4326);
                etablissementRepository.save(e21);

                Etablissement e22 = new Etablissement();
                e22.setNom("Hôtel Escale");
                e22.setAdresse("Ivato");
                e22.setTelephone("+261 38 26 954 03");
                e22.setPrixMoyen(new BigDecimal("207000"));
                e22.setNote(new BigDecimal("3"));
                e22.setPhotos(Arrays.asList("escale1.jpg", "escale2.jpg", "escale3.jpg"));
                e22.setDescription("Bienvenue à Hôtel Escale. Situé dans le quartier de Ivato.");
                e22.setCategorie(hotel);
                e22.setGeom(geometryFactory.createPoint(new Coordinate(47.473011, -18.802827)));
                e22.getGeom().setSRID(4326);
                etablissementRepository.save(e22);

                Etablissement e23 = new Etablissement();
                e23.setNom("Anjary Hotel Antananarivo");
                e23.setAdresse("Tsaralalana");
                e23.setTelephone("+261 34 22 279 58");
                e23.setPrixMoyen(new BigDecimal("378000"));
                e23.setNote(new BigDecimal("2"));
                e23.setPhotos(Arrays.asList("anjary1.jpg", "anjary2.jpg", "anjary3.jpg"));
                e23.setDescription("Bienvenue à Anjary Hotel Antananarivo. Situé dans le quartier de Tsaralalana.");
                e23.setCategorie(hotel);
                e23.setGeom(geometryFactory.createPoint(new Coordinate(47.518682, -18.907965)));
                e23.getGeom().setSRID(4326);
                etablissementRepository.save(e23);

                Etablissement e24 = new Etablissement();
                e24.setNom("Havana Resort");
                e24.setAdresse("Ambodihady");
                e24.setTelephone("+261 34 05 889 10");
                e24.setPrixMoyen(new BigDecimal("252000"));
                e24.setNote(new BigDecimal("4"));
                e24.setPhotos(Arrays.asList("havana1.jpg", "havana2.jpg", "havana3.jpg"));
                e24.setDescription("Bienvenue à Havana Resort. Situé dans le quartier de Ambodihady.");
                e24.setCategorie(hotel);
                e24.setGeom(geometryFactory.createPoint(new Coordinate(47.526172, -18.912738)));
                e24.getGeom().setSRID(4326);
                etablissementRepository.save(e24);

                Etablissement e25 = new Etablissement();
                e25.setNom("Les 3 Métis");
                e25.setAdresse("Antaninandro");
                e25.setTelephone("+261 33 05 520 20");
                e25.setPrixMoyen(new BigDecimal("270000"));
                e25.setNote(new BigDecimal("2"));
                e25.setPhotos(Arrays.asList("troismetis1.jpg", "troismetis2.jpg", "troismetis3.jpg"));
                e25.setDescription("Bienvenue à Les 3 Métis. Situé dans le quartier de Antaninandro.");
                e25.setCategorie(hotel);
                e25.setGeom(geometryFactory.createPoint(new Coordinate(47.529443, -18.903330)));
                e25.getGeom().setSRID(4326);
                etablissementRepository.save(e25);

                Etablissement e26 = new Etablissement();
                e26.setNom("Hôtel Colbert - SPA & Casino");
                e26.setAdresse("Antaninarenina");
                e26.setTelephone("+261 20 22 202 02");
                e26.setPrixMoyen(new BigDecimal("342000"));
                e26.setNote(new BigDecimal("4"));
                e26.setPhotos(Arrays.asList("colbert1.jpg", "colbert2.jpg", "colbert3.jpg", "colbert4.jpg"));
                e26.setDescription("Bienvenue à Hôtel Colbert - SPA & Casino. Situé dans le quartier de Antaninarenina.");
                e26.setCategorie(hotel);
                e26.setGeom(geometryFactory.createPoint(new Coordinate(47.525370, -18.911310)));
                e26.getGeom().setSRID(4326);
                etablissementRepository.save(e26);

                Etablissement e27 = new Etablissement();
                e27.setNom("Le Grand Mellis");
                e27.setAdresse("Tsaralalana");
                e27.setTelephone("+261 20 22 234 25");
                e27.setPrixMoyen(new BigDecimal("270000"));
                e27.setNote(new BigDecimal("4"));
                e27.setPhotos(Arrays.asList("grandmellis1.jpg", "grandmellis2.jpg", "grandmellis3.jpg", "grandmellis4.jpg"));
                e27.setDescription("Bienvenue à Le Grand Mellis. Situé dans le quartier de Tsaralalana.");
                e27.setCategorie(hotel);
                e27.setGeom(geometryFactory.createPoint(new Coordinate(47.522682, -18.905991)));
                e27.getGeom().setSRID(4326);
                etablissementRepository.save(e27);

                Etablissement e28 = new Etablissement();
                e28.setNom("Taj Hotel Madagascar");
                e28.setAdresse("Tsaralalana");
                e28.setTelephone("+261 34 26 451 81");
                e28.setPrixMoyen(new BigDecimal("121500"));
                e28.setNote(new BigDecimal("2"));
                e28.setPhotos(Arrays.asList("taj1.jpg", "taj2.jpg"));
                e28.setDescription("Bienvenue à Taj Hotel Madagascar. Situé dans le quartier de Tsaralalana.");
                e28.setCategorie(hotel);
                e28.setGeom(geometryFactory.createPoint(new Coordinate(47.521011, -18.907335)));
                e28.getGeom().setSRID(4326);
                etablissementRepository.save(e28);

                Etablissement e29 = new Etablissement();
                e29.setNom("Motel Anosy");
                e29.setAdresse("Anosy");
                e29.setTelephone("+261 34 75 185 50");
                e29.setPrixMoyen(new BigDecimal("166500"));
                e29.setNote(new BigDecimal("2"));
                e29.setPhotos(Arrays.asList("motel1.jpg", "motel2.jpg", "motel3.jpg"));
                e29.setDescription("Bienvenue à Motel Anosy. Situé dans le quartier de Anosy.");
                e29.setCategorie(hotel);
                e29.setGeom(geometryFactory.createPoint(new Coordinate(47.518749, -18.921378)));
                e29.getGeom().setSRID(4326);
                etablissementRepository.save(e29);

                Etablissement e30 = new Etablissement();
                e30.setNom("Le Louvre Hôtel & Spa");
                e30.setAdresse("Avenue Philibert Tsiranana");
                e30.setTelephone("+261 20 22 390 00");
                e30.setPrixMoyen(new BigDecimal("364500"));
                e30.setNote(new BigDecimal("4"));
                e30.setPhotos(Arrays.asList("lelouvre1.jpg", "lelouvre2.jpg", "lelouvre3.jpg"));
                e30.setDescription("Bienvenue à Le Louvre Hôtel & Spa. Situé dans le quartier de Avenue Philibert Tsiranana.");
                e30.setCategorie(hotel);
                e30.setGeom(geometryFactory.createPoint(new Coordinate(47.524841, -18.910288)));
                e30.getGeom().setSRID(4326);
                etablissementRepository.save(e30);

                Etablissement e31 = new Etablissement();
                e31.setNom("Le Fred");
                e31.setAdresse("Avenue Freddy Rajaofera");
                e31.setTelephone("+261 33 15 700 15");
                e31.setPrixMoyen(new BigDecimal("274500"));
                e31.setNote(new BigDecimal("3"));
                e31.setPhotos(Arrays.asList("lefred1.jpg", "lefred2.jpg", "lefred3.jpg"));
                e31.setDescription("Bienvenue à Le Fred. Situé dans le quartier de Avenue Freddy Rajaofera.");
                e31.setCategorie(hotel);
                e31.setGeom(geometryFactory.createPoint(new Coordinate(47.528820, -18.904889)));
                e31.getGeom().setSRID(4326);
                etablissementRepository.save(e31);

                Etablissement e32 = new Etablissement();
                e32.setNom("Hôtel La Maison Lovasoa");
                e32.setAdresse("Ambohijatovo");
                e32.setTelephone("+261 38 11 807 71");
                e32.setPrixMoyen(new BigDecimal("108000"));
                e32.setNote(new BigDecimal("2"));
                e32.setPhotos(Arrays.asList("lovasoa1.jpg", "lovasoa2.jpg"));
                e32.setDescription("Bienvenue à Hôtel La Maison Lovasoa. Situé dans le quartier de Ambohijatovo.");
                e32.setCategorie(hotel);
                e32.setGeom(geometryFactory.createPoint(new Coordinate(47.529125, -18.913726)));
                e32.getGeom().setSRID(4326);
                etablissementRepository.save(e32);

                Etablissement e33 = new Etablissement();
                e33.setNom("Le Palmier Tana");
                e33.setAdresse("Faravohitra");
                e33.setTelephone("+261 34 80 616 23");
                e33.setPrixMoyen(new BigDecimal("270000"));
                e33.setNote(new BigDecimal("3"));
                e33.setPhotos(Arrays.asList("palmier1.jpg", "palmier2.jpg"));
                e33.setDescription("Bienvenue à Le Palmier Tana. Situé dans le quartier de Faravohitra.");
                e33.setCategorie(hotel);
                e33.setGeom(geometryFactory.createPoint(new Coordinate(47.528246, -18.906186)));
                e33.getGeom().setSRID(4326);
                etablissementRepository.save(e33);

                Etablissement e34 = new Etablissement();
                e34.setNom("Grand Hotel Urban");
                e34.setAdresse("Ambatovinaky");
                e34.setTelephone("+261 20 22 209 80");
                e34.setPrixMoyen(new BigDecimal("441000"));
                e34.setNote(new BigDecimal("4"));
                e34.setPhotos(Arrays.asList("urban1.jpg", "urban2.jpg", "urban3.jpg"));
                e34.setDescription("Bienvenue à Grand Hotel Urban. Situé dans le quartier de Ambatovinaky.");
                e34.setCategorie(hotel);
                e34.setGeom(geometryFactory.createPoint(new Coordinate(47.528316, -18.913680)));
                e34.getGeom().setSRID(4326);
                etablissementRepository.save(e34);

                Etablissement e35 = new Etablissement();
                e35.setNom("Residence du Rova");
                e35.setAdresse("Ambohijatovo");
                e35.setTelephone("+261 20 22 341 46");
                e35.setPrixMoyen(new BigDecimal("180000"));
                e35.setNote(new BigDecimal("3"));
                e35.setPhotos(Arrays.asList("rova1.jpg", "rova2.jpg"));
                e35.setDescription("Bienvenue à Residence du Rova. Situé dans le quartier de Ambohijatovo.");
                e35.setCategorie(hotel);
                e35.setGeom(geometryFactory.createPoint(new Coordinate(47.531834, -18.915131)));
                e35.getGeom().setSRID(4326);
                etablissementRepository.save(e35);

                Etablissement e36 = new Etablissement();
                e36.setNom("Hotel Evergreen");
                e36.setAdresse("Ampandrana");
                e36.setTelephone("+261 20 22 341 46");
                e36.setPrixMoyen(new BigDecimal("162000"));
                e36.setNote(new BigDecimal("3"));
                e36.setPhotos(Arrays.asList("evergreen1.jpg", "evergreen2.jpg", "evergreen3.jpg"));
                e36.setDescription("Bienvenue à Hotel Evergreen. Situé dans le quartier de Ampandrana.");
                e36.setCategorie(hotel);
                e36.setGeom(geometryFactory.createPoint(new Coordinate(47.533568, -18.905441)));
                e36.getGeom().setSRID(4326);
                etablissementRepository.save(e36);

                Etablissement e37 = new Etablissement();
                e37.setNom("Tana-Jacaranda Hotel");
                e37.setAdresse("Rue Rainitsarovy");
                e37.setTelephone("+261 20 22 562 39");
                e37.setPrixMoyen(new BigDecimal("81000"));
                e37.setNote(new BigDecimal("1"));
                e37.setPhotos(Arrays.asList("jacaranda1.jpg", "jacaranda2.jpg"));
                e37.setDescription("Bienvenue à Tana-Jacaranda Hotel. Situé dans le quartier de Rue Rainitsarovy.");
                e37.setCategorie(hotel);
                e37.setGeom(geometryFactory.createPoint(new Coordinate(47.521577, -18.911779)));
                e37.getGeom().setSRID(4326);
                etablissementRepository.save(e37);

                Etablissement e38 = new Etablissement();
                e38.setNom("Hotel Le Pousse Pousse");
                e38.setAdresse("Antaninarenina");
                e38.setTelephone("+261 32 42 052 62");
                e38.setPrixMoyen(new BigDecimal("108000"));
                e38.setNote(new BigDecimal("3"));
                e38.setPhotos(Arrays.asList("poussepousse1.jpg", "poussepousse2.jpg"));
                e38.setDescription("Bienvenue à Hotel Le Pousse Pousse. Situé dans le quartier de Antaninarenina.");
                e38.setCategorie(hotel);
                e38.setGeom(geometryFactory.createPoint(new Coordinate(47.523562, -18.910421)));
                e38.getGeom().setSRID(4326);
                etablissementRepository.save(e38);

                Etablissement e39 = new Etablissement();
                e39.setNom("Sky Blue Hotel Espace");
                e39.setAdresse("Alasora");
                e39.setTelephone("+261 33 70 220 13");
                e39.setPrixMoyen(new BigDecimal("144000"));
                e39.setNote(new BigDecimal("3"));
                e39.setPhotos(Arrays.asList("skyblue1.jpg", "skyblue2.jpg", "skyblue3.jpg"));
                e39.setDescription("Bienvenue à Sky Blue Hotel Espace. Situé dans le quartier de Alasora.");
                e39.setCategorie(hotel);
                e39.setGeom(geometryFactory.createPoint(new Coordinate(47.565837, -18.935810)));
                e39.getGeom().setSRID(4326);
                etablissementRepository.save(e39);

                Etablissement e40 = new Etablissement();
                e40.setNom("A L'Hotel");
                e40.setAdresse("Ambanidia");
                e40.setTelephone("+261 32 05 536 86");
                e40.setPrixMoyen(new BigDecimal("90000"));
                e40.setNote(new BigDecimal("3"));
                e40.setPhotos(Arrays.asList("motel3.jpg", "motel2.jpg", "motel1.jpg"));
                e40.setDescription("Bienvenue à A L'Hotel. Situé dans le quartier de Ambanidia.");
                e40.setCategorie(hotel);
                e40.setGeom(geometryFactory.createPoint(new Coordinate(47.536901, -18.919871)));
                e40.getGeom().setSRID(4326);
                etablissementRepository.save(e40);

                Etablissement e41 = new Etablissement();
                e41.setNom("La Casa Blu");
                e41.setAdresse("Ampasamadinika");
                e41.setTelephone("+261 34 14 757 83");
                e41.setPrixMoyen(new BigDecimal("117000"));
                e41.setNote(new BigDecimal("2"));
                e41.setPhotos(Arrays.asList("telomiova2.jpg", "telomiova.jpg", "telomiova3.jpg"));
                e41.setDescription("Bienvenue à La Casa Blu. Situé dans le quartier de Ampasamadinika.");
                e41.setCategorie(hotel);
                e41.setGeom(geometryFactory.createPoint(new Coordinate(47.520352, -18.910404)));
                e41.getGeom().setSRID(4326);
                etablissementRepository.save(e41);

                Etablissement e42 = new Etablissement();
                e42.setNom("Delta Hotels by Marriott Antananarivo");
                e42.setAdresse("Antanimena");
                e42.setTelephone("+261 20 22 640 04");
                e42.setPrixMoyen(new BigDecimal("567000"));
                e42.setNote(new BigDecimal("4"));
                e42.setPhotos(Arrays.asList("motel3.jpg", "motel2.jpg", "motel1.jpg"));
                e42.setDescription("Bienvenue à Delta Hotels by Marriott Antananarivo. Situé dans le quartier de Antanimena.");
                e42.setCategorie(hotel);
                e42.setGeom(geometryFactory.createPoint(new Coordinate(47.521077, -18.899393)));
                e42.getGeom().setSRID(4326);
                etablissementRepository.save(e42);

                Etablissement e43 = new Etablissement();
                e43.setNom("Mercure Hotel Alarobia");
                e43.setAdresse("Alarobia / Ivandry");
                e43.setTelephone("+261 32 11 488 88");
                e43.setPrixMoyen(new BigDecimal("252000"));
                e43.setNote(new BigDecimal("2"));
                e43.setPhotos(Arrays.asList("telomiova2.jpg", "telomiova.jpg", "telomiova3.jpg"));
                e43.setDescription("Bienvenue à Mercure Hotel Alarobia. Situé dans le quartier de Alarobia / Ivandry.");
                e43.setCategorie(hotel);
                e43.setGeom(geometryFactory.createPoint(new Coordinate(47.519115, -18.872284)));
                e43.getGeom().setSRID(4326);
                etablissementRepository.save(e43);

                Etablissement e44 = new Etablissement();
                e44.setNom("Novotel Convention & Spa Antananarivo");
                e44.setAdresse("Ivandry");
                e44.setTelephone("+261 20 23 777 77");
                e44.setPrixMoyen(new BigDecimal("648000"));
                e44.setNote(new BigDecimal("5"));
                e44.setPhotos(Arrays.asList("motel3.jpg", "motel2.jpg", "motel1.jpg"));
                e44.setDescription("Bienvenue à Novotel Convention & Spa Antananarivo. Situé dans le quartier de Ivandry.");
                e44.setCategorie(hotel);
                e44.setGeom(geometryFactory.createPoint(new Coordinate(47.522694, -18.872846)));
                e44.getGeom().setSRID(4326);
                etablissementRepository.save(e44);

                Etablissement e45 = new Etablissement();
                e45.setNom("Ibis Antananarivo Ankorondrano");
                e45.setAdresse("Ankorondrano");
                e45.setTelephone("+261 20 97 333 33");
                e45.setPrixMoyen(new BigDecimal("468000"));
                e45.setNote(new BigDecimal("3"));
                e45.setPhotos(Arrays.asList("lefred1.jpg", "lefred2.jpg", "lefred3.jpg"));
                e45.setDescription("Bienvenue à Ibis Antananarivo Ankorondrano. Situé dans le quartier de Ankorondrano.");
                e45.setCategorie(hotel);
                e45.setGeom(geometryFactory.createPoint(new Coordinate(47.521959, -18.879157)));
                e45.getGeom().setSRID(4326);
                etablissementRepository.save(e45);

                Etablissement e46 = new Etablissement();
                e46.setNom("Iarimbato Hotel & SPA");
                e46.setAdresse("Ankadikely");
                e46.setTelephone("+261 38 20 417 77");
                e46.setPrixMoyen(new BigDecimal("112500"));
                e46.setNote(new BigDecimal("3"));
                e46.setPhotos(Arrays.asList("motel3.jpg", "motel2.jpg", "motel1.jpg"));
                e46.setDescription("Bienvenue à Iarimbato Hotel & SPA. Situé dans le quartier de Ankadikely.");
                e46.setCategorie(hotel);
                e46.setGeom(geometryFactory.createPoint(new Coordinate(47.552828, -18.846825)));
                e46.getGeom().setSRID(4326);
                etablissementRepository.save(e46);

                Etablissement e47 = new Etablissement();
                e47.setNom("Hotel Paon d'Or");
                e47.setAdresse("Antanetibe");
                e47.setTelephone("+261 33 05 622 33");
                e47.setPrixMoyen(new BigDecimal("319500"));
                e47.setNote(new BigDecimal("3"));
                e47.setPhotos(Arrays.asList("tsanga1.jpg", "tsanga2.jpg"));
                e47.setDescription("Bienvenue à Hotel Paon d'Or. Situé dans le quartier de Antanetibe.");
                e47.setCategorie(hotel);
                e47.setGeom(geometryFactory.createPoint(new Coordinate(47.470234, -18.835885)));
                e47.getGeom().setSRID(4326);
                etablissementRepository.save(e47);

                Etablissement e48 = new Etablissement();
                e48.setNom("Hôtel Le Safran");
                e48.setAdresse("Ambohibao");
                e48.setTelephone("+261 32 42 547 06");
                e48.setPrixMoyen(new BigDecimal("45000"));
                e48.setNote(new BigDecimal("1"));
                e48.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e48.setDescription("Bienvenue à Hôtel Le Safran. Situé dans le quartier de Ambohibao.");
                e48.setCategorie(hotel);
                e48.setGeom(geometryFactory.createPoint(new Coordinate(47.477620, -18.849919)));
                e48.getGeom().setSRID(4326);
                etablissementRepository.save(e48);

                Etablissement e49 = new Etablissement();
                e49.setNom("Relais des Plateaux Hotel & Spa");
                e49.setAdresse("Talatamaty");
                e49.setTelephone("+261 32 05 678 93");
                e49.setPrixMoyen(new BigDecimal("346500"));
                e49.setNote(new BigDecimal("4"));
                e49.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e49.setDescription("Bienvenue à Relais des Plateaux Hotel & Spa. Situé dans le quartier de Talatamaty.");
                e49.setCategorie(hotel);
                e49.setGeom(geometryFactory.createPoint(new Coordinate(47.463052, -18.834140)));
                e49.getGeom().setSRID(4326);
                etablissementRepository.save(e49);

                Etablissement e50 = new Etablissement();
                e50.setNom("Le Combava");
                e50.setAdresse("Ambodihady");
                e50.setTelephone("+261 32 11 584 95");
                e50.setPrixMoyen(new BigDecimal("247500"));
                e50.setNote(new BigDecimal("3"));
                e50.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e50.setDescription("Bienvenue à Le Combava. Situé dans le quartier de Ambodihady.");
                e50.setCategorie(hotel);
                e50.setGeom(geometryFactory.createPoint(new Coordinate(47.486192, -18.871359)));
                e50.getGeom().setSRID(4326);
                etablissementRepository.save(e50);

                Etablissement e51 = new Etablissement();
                e51.setNom("Madagascar Golden Peacock Hotel");
                e51.setAdresse("Antanetibe");
                e51.setTelephone("+261 33 05 622 33");
                e51.setPrixMoyen(new BigDecimal("216000"));
                e51.setNote(new BigDecimal("5"));
                e51.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e51.setDescription("Bienvenue à Madagascar Golden Peacock Hotel. Situé dans le quartier de Antanetibe.");
                e51.setCategorie(hotel);
                e51.setGeom(geometryFactory.createPoint(new Coordinate(47.469876, -18.835178)));
                e51.getGeom().setSRID(4326);
                etablissementRepository.save(e51);

                Etablissement e52 = new Etablissement();
                e52.setNom("Hôtel Belvedere");
                e52.setAdresse("Isoraka");
                e52.setTelephone("");
                e52.setPrixMoyen(new BigDecimal("193500"));
                e52.setNote(new BigDecimal("2"));
                e52.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e52.setDescription("Bienvenue à Hôtel Belvedere. Situé dans le quartier de Isoraka.");
                e52.setCategorie(hotel);
                e52.setGeom(geometryFactory.createPoint(new Coordinate(47.518160, -18.909738)));
                e52.getGeom().setSRID(4326);
                etablissementRepository.save(e52);

                Etablissement e53 = new Etablissement();
                e53.setNom("Samsara Hotel");
                e53.setAdresse("Antsahavola");
                e53.setTelephone("+261 34 58 863 14");
                e53.setPrixMoyen(new BigDecimal("261000"));
                e53.setNote(new BigDecimal("3"));
                e53.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e53.setDescription("Bienvenue à Samsara Hotel. Situé dans le quartier de Antsahavola.");
                e53.setCategorie(hotel);
                e53.setGeom(geometryFactory.createPoint(new Coordinate(47.521498, -18.907972)));
                e53.getGeom().setSRID(4326);
                etablissementRepository.save(e53);

                Etablissement e54 = new Etablissement();
                e54.setNom("Au Bois Vert Hôtel Antananarivo");
                e54.setAdresse("Ivato");
                e54.setTelephone("+261 34 02 447 26");
                e54.setPrixMoyen(new BigDecimal("432000"));
                e54.setNote(new BigDecimal("4"));
                e54.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e54.setDescription("Bienvenue à Au Bois Vert Hôtel Antananarivo. Situé dans le quartier de Ivato.");
                e54.setCategorie(hotel);
                e54.setGeom(geometryFactory.createPoint(new Coordinate(47.491145, -18.823646)));
                e54.getGeom().setSRID(4326);
                etablissementRepository.save(e54);

                Etablissement e55 = new Etablissement();
                e55.setNom("Andriana Luxury");
                e55.setAdresse("Antananarivo Centre (Haute Ville)");
                e55.setTelephone("+261 38 71 076 72");
                e55.setPrixMoyen(new BigDecimal("387000"));
                e55.setNote(new BigDecimal("3"));
                e55.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e55.setDescription("Bienvenue à Andriana Luxury. Situé dans le quartier de Antananarivo Centre (Haute Ville).");
                e55.setCategorie(hotel);
                e55.setGeom(geometryFactory.createPoint(new Coordinate(47.531053, -18.917017)));
                e55.getGeom().setSRID(4326);
                etablissementRepository.save(e55);

                Etablissement e56 = new Etablissement();
                e56.setNom("Hôtel Panorama");
                e56.setAdresse("Andrainarivo");
                e56.setTelephone("+261 20 22 409 65");
                e56.setPrixMoyen(new BigDecimal("270000"));
                e56.setNote(new BigDecimal("3"));
                e56.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e56.setDescription("Bienvenue à Hôtel Panorama. Situé dans le quartier de Andrainarivo.");
                e56.setCategorie(hotel);
                e56.setGeom(geometryFactory.createPoint(new Coordinate(47.543370, -18.910474)));
                e56.getGeom().setSRID(4326);
                etablissementRepository.save(e56);

                Etablissement e57 = new Etablissement();
                e57.setNom("Ivotel");
                e57.setAdresse("Ambohidahy");
                e57.setTelephone("+261 38 22 227 16");
                e57.setPrixMoyen(new BigDecimal("153000"));
                e57.setNote(new BigDecimal("3"));
                e57.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e57.setDescription("Bienvenue à Ivotel. Situé dans le quartier de Ambohidahy.");
                e57.setCategorie(hotel);
                e57.setGeom(geometryFactory.createPoint(new Coordinate(47.526222, -18.912786)));
                e57.getGeom().setSRID(4326);
                etablissementRepository.save(e57);

                Etablissement e58 = new Etablissement();
                e58.setNom("Avamada Lodge");
                e58.setAdresse("Ivato");
                e58.setTelephone("+261 33 84 754 97");
                e58.setPrixMoyen(new BigDecimal("130500"));
                e58.setNote(new BigDecimal("2"));
                e58.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e58.setDescription("Bienvenue à Avamada Lodge. Situé dans le quartier de Ivato.");
                e58.setCategorie(hotel);
                e58.setGeom(geometryFactory.createPoint(new Coordinate(47.468644, -18.825834)));
                e58.getGeom().setSRID(4326);
                etablissementRepository.save(e58);

                Etablissement e59 = new Etablissement();
                e59.setNom("Meva Guesthouse");
                e59.setAdresse("Talatamaty");
                e59.setTelephone("+261 32 42 896 62");
                e59.setPrixMoyen(new BigDecimal("225000"));
                e59.setNote(new BigDecimal("3"));
                e59.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e59.setDescription("Bienvenue à Meva Guesthouse. Situé dans le quartier de Talatamaty.");
                e59.setCategorie(hotel);
                e59.setGeom(geometryFactory.createPoint(new Coordinate(47.465075, -18.845730)));
                e59.getGeom().setSRID(4326);
                etablissementRepository.save(e59);

                Etablissement e60 = new Etablissement();
                e60.setNom("Ivato Hôtel - Hôtel 1 étoile");
                e60.setAdresse("Ivato");
                e60.setTelephone("+261 34 22 445 10");
                e60.setPrixMoyen(new BigDecimal("225000"));
                e60.setNote(new BigDecimal("3"));
                e60.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e60.setDescription("Bienvenue à Ivato Hôtel - Hôtel 1 étoile. Situé dans le quartier de Ivato.");
                e60.setCategorie(hotel);
                e60.setGeom(geometryFactory.createPoint(new Coordinate(47.487193, -18.824066)));
                e60.getGeom().setSRID(4326);
                etablissementRepository.save(e60);

                Etablissement e61 = new Etablissement();
                e61.setNom("Le Felix");
                e61.setAdresse("Mahamasina");
                e61.setTelephone("+261 38 73 092 83");
                e61.setPrixMoyen(new BigDecimal("225000"));
                e61.setNote(new BigDecimal("3"));
                e61.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e61.setDescription("Bienvenue à Le Felix. Situé dans le quartier de Mahamasina.");
                e61.setCategorie(hotel);
                e61.setGeom(geometryFactory.createPoint(new Coordinate(47.528081, -18.917241)));
                e61.getGeom().setSRID(4326);
                etablissementRepository.save(e61);

                Etablissement e62 = new Etablissement();
                e62.setNom("Lorenzo Guest House");
                e62.setAdresse("Androhibe");
                e62.setTelephone("+261 20 22 427 76");
                e62.setPrixMoyen(new BigDecimal("225000"));
                e62.setNote(new BigDecimal("3"));
                e62.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e62.setDescription("Bienvenue à Lorenzo Guest House. Situé dans le quartier de Androhibe.");
                e62.setCategorie(hotel);
                e62.setGeom(geometryFactory.createPoint(new Coordinate(47.543968, -18.866397)));
                e62.getGeom().setSRID(4326);
                etablissementRepository.save(e62);

                Etablissement e63 = new Etablissement();
                e63.setNom("Ampifitia Guest House Antananarivo");
                e63.setAdresse("Antananarivo");
                e63.setTelephone("+49 1514 2439208");
                e63.setPrixMoyen(new BigDecimal("225000"));
                e63.setNote(new BigDecimal("3"));
                e63.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e63.setDescription("Bienvenue à Ampifitia Guest House Antananarivo. Situé dans le quartier de Antananarivo.");
                e63.setCategorie(hotel);
                e63.setGeom(geometryFactory.createPoint(new Coordinate(47.563073, -18.942237)));
                e63.getGeom().setSRID(4326);
                etablissementRepository.save(e63);

                Etablissement e64 = new Etablissement();
                e64.setNom("Le Karthala Guest House");
                e64.setAdresse("Mandrosoa");
                e64.setTelephone("+261 33 11 971 56");
                e64.setPrixMoyen(new BigDecimal("225000"));
                e64.setNote(new BigDecimal("3"));
                e64.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e64.setDescription("Bienvenue à Le Karthala Guest House. Situé dans le quartier de Mandrosoa.");
                e64.setCategorie(hotel);
                e64.setGeom(geometryFactory.createPoint(new Coordinate(47.529072, -18.909610)));
                e64.getGeom().setSRID(4326);
                etablissementRepository.save(e64);

                Etablissement e65 = new Etablissement();
                e65.setNom("Petite Flower Guest House");
                e65.setAdresse("Ivato");
                e65.setTelephone("+261 34 64 528 90");
                e65.setPrixMoyen(new BigDecimal("225000"));
                e65.setNote(new BigDecimal("3"));
                e65.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e65.setDescription("Bienvenue à Petite Flower Guest House. Situé dans le quartier de Ivato.");
                e65.setCategorie(hotel);
                e65.setGeom(geometryFactory.createPoint(new Coordinate(47.463303, -18.814829)));
                e65.getGeom().setSRID(4326);
                etablissementRepository.save(e65);

                Etablissement e66 = new Etablissement();
                e66.setNom("Guest House Nohfy");
                e66.setAdresse("Ambohijanahary");
                e66.setTelephone("+261 38 55 234 55");
                e66.setPrixMoyen(new BigDecimal("225000"));
                e66.setNote(new BigDecimal("3"));
                e66.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e66.setDescription("Bienvenue à Guest House Nohfy. Situé dans le quartier de Ambohijanahary.");
                e66.setCategorie(hotel);
                e66.setGeom(geometryFactory.createPoint(new Coordinate(47.490900, -18.831194)));
                e66.getGeom().setSRID(4326);
                etablissementRepository.save(e66);

                Etablissement e67 = new Etablissement();
                e67.setNom("Antsaharena Guest House");
                e67.setAdresse("Antananarivo");
                e67.setTelephone("+261 34 05 524 94");
                e67.setPrixMoyen(new BigDecimal("225000"));
                e67.setNote(new BigDecimal("3"));
                e67.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e67.setDescription("Bienvenue à Antsaharena Guest House. Situé dans le quartier de Antananarivo.");
                e67.setCategorie(hotel);
                e67.setGeom(geometryFactory.createPoint(new Coordinate(47.554039, -18.864093)));
                e67.getGeom().setSRID(4326);
                etablissementRepository.save(e67);

                Etablissement e68 = new Etablissement();
                e68.setNom("RHV Guest House");
                e68.setAdresse("Anjomakely / Ivato");
                e68.setTelephone("+261 33 11 062 99");
                e68.setPrixMoyen(new BigDecimal("225000"));
                e68.setNote(new BigDecimal("3"));
                e68.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e68.setDescription("Bienvenue à RHV Guest House. Situé dans le quartier de Anjomakely / Ivato.");
                e68.setCategorie(hotel);
                e68.setGeom(geometryFactory.createPoint(new Coordinate(47.491151, -18.777455)));
                e68.getGeom().setSRID(4326);
                etablissementRepository.save(e68);

                Etablissement e69 = new Etablissement();
                e69.setNom("Auberge de la Ferme d'Ivato");
                e69.setAdresse("Ivato");
                e69.setTelephone("+261 32 11 594 93");
                e69.setPrixMoyen(new BigDecimal("225000"));
                e69.setNote(new BigDecimal("3"));
                e69.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e69.setDescription("Bienvenue à Auberge de la Ferme d'Ivato. Situé dans le quartier de Ivato.");
                e69.setCategorie(hotel);
                e69.setGeom(geometryFactory.createPoint(new Coordinate(47.459824, -18.782505)));
                e69.getGeom().setSRID(4326);
                etablissementRepository.save(e69);

                Etablissement e70 = new Etablissement();
                e70.setNom("Auberge Chez Jeanne");
                e70.setAdresse("Talatamaty");
                e70.setTelephone("+261 32 02 643 97");
                e70.setPrixMoyen(new BigDecimal("225000"));
                e70.setNote(new BigDecimal("3"));
                e70.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e70.setDescription("Bienvenue à Auberge Chez Jeanne. Situé dans le quartier de Talatamaty.");
                e70.setCategorie(hotel);
                e70.setGeom(geometryFactory.createPoint(new Coordinate(47.448960, -18.842379)));
                e70.getGeom().setSRID(4326);
                etablissementRepository.save(e70);

                Etablissement e71 = new Etablissement();
                e71.setNom("G&V Inn - Gasy & Vahiny Auberge");
                e71.setAdresse("Antananarivo Ouest");
                e71.setTelephone("+261 38 12 210 32");
                e71.setPrixMoyen(new BigDecimal("225000"));
                e71.setNote(new BigDecimal("3"));
                e71.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e71.setDescription("Bienvenue à G&V Inn - Gasy & Vahiny Auberge. Situé dans le quartier de Antananarivo Ouest.");
                e71.setCategorie(hotel);
                e71.setGeom(geometryFactory.createPoint(new Coordinate(47.519488, -18.926406)));
                e71.getGeom().setSRID(4326);
                etablissementRepository.save(e71);

                Etablissement e72 = new Etablissement();
                e72.setNom("Auberge Bora Bora");
                e72.setAdresse("Alasora");
                e72.setTelephone("+261 34 64 874 35");
                e72.setPrixMoyen(new BigDecimal("225000"));
                e72.setNote(new BigDecimal("3"));
                e72.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e72.setDescription("Bienvenue à Auberge Bora Bora. Situé dans le quartier de Alasora.");
                e72.setCategorie(hotel);
                e72.setGeom(geometryFactory.createPoint(new Coordinate(47.585713, -18.965156)));
                e72.getGeom().setSRID(4326);
                etablissementRepository.save(e72);

                Etablissement e73 = new Etablissement();
                e73.setNom("Restaurant Studio Auberge");
                e73.setAdresse("Ivato Aéroport");
                e73.setTelephone("+261 32 05 260 96");
                e73.setPrixMoyen(new BigDecimal("225000"));
                e73.setNote(new BigDecimal("3"));
                e73.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e73.setDescription("Bienvenue à Restaurant Studio Auberge. Situé dans le quartier de Ivato Aéroport.");
                e73.setCategorie(hotel);
                e73.setGeom(geometryFactory.createPoint(new Coordinate(47.487689, -18.824561)));
                e73.getGeom().setSRID(4326);
                etablissementRepository.save(e73);

                Etablissement e74 = new Etablissement();
                e74.setNom("Auberge Tanàna Kely");
                e74.setAdresse("Vontovorona");
                e74.setTelephone("+261 32 05 543 29");
                e74.setPrixMoyen(new BigDecimal("225000"));
                e74.setNote(new BigDecimal("3"));
                e74.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e74.setDescription("Bienvenue à Auberge Tanàna Kely. Situé dans le quartier de Vontovorona.");
                e74.setCategorie(hotel);
                e74.setGeom(geometryFactory.createPoint(new Coordinate(47.432952, -18.975324)));
                e74.getGeom().setSRID(4326);
                etablissementRepository.save(e74);

                Etablissement e75 = new Etablissement();
                e75.setNom("Residence Sidi Ivandry");
                e75.setAdresse("Ivandry");
                e75.setTelephone("");
                e75.setPrixMoyen(new BigDecimal("225000"));
                e75.setNote(new BigDecimal("3"));
                e75.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e75.setDescription("Bienvenue à Residence Sidi Ivandry. Situé dans le quartier de Ivandry.");
                e75.setCategorie(hotel);
                e75.setGeom(geometryFactory.createPoint(new Coordinate(47.527707, -18.864943)));
                e75.getGeom().setSRID(4326);
                etablissementRepository.save(e75);

                Etablissement e76 = new Etablissement();
                e76.setNom("Résidence Le Hublot");
                e76.setAdresse("Analakely");
                e76.setTelephone("+261 34 31 545 00");
                e76.setPrixMoyen(new BigDecimal("225000"));
                e76.setNote(new BigDecimal("3"));
                e76.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e76.setDescription("Bienvenue à Résidence Le Hublot. Situé dans le quartier de Analakely.");
                e76.setCategorie(hotel);
                e76.setGeom(geometryFactory.createPoint(new Coordinate(47.523917, -18.909145)));
                e76.getGeom().setSRID(4326);
                etablissementRepository.save(e76);

                Etablissement e77 = new Etablissement();
                e77.setNom("Residence Lantana");
                e77.setAdresse("Mahamasina");
                e77.setTelephone("+261 20 22 258 86");
                e77.setPrixMoyen(new BigDecimal("225000"));
                e77.setNote(new BigDecimal("3"));
                e77.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e77.setDescription("Bienvenue à Residence Lantana. Situé dans le quartier de Mahamasina.");
                e77.setCategorie(hotel);
                e77.setGeom(geometryFactory.createPoint(new Coordinate(47.524221, -18.921109)));
                e77.getGeom().setSRID(4326);
                etablissementRepository.save(e77);

                Etablissement e78 = new Etablissement();
                e78.setNom("Anouk Hotel");
                e78.setAdresse("Ivato");
                e78.setTelephone("+261 38 75 194 30");
                e78.setPrixMoyen(new BigDecimal("225000"));
                e78.setNote(new BigDecimal("3"));
                e78.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e78.setDescription("Bienvenue à Anouk Hotel. Situé dans le quartier de Ivato.");
                e78.setCategorie(hotel);
                e78.setGeom(geometryFactory.createPoint(new Coordinate(47.463647, -18.834132)));
                e78.getGeom().setSRID(4326);
                etablissementRepository.save(e78);

                Etablissement e79 = new Etablissement();
                e79.setNom("Résidence Atlantis");
                e79.setAdresse("Ankadindramamy");
                e79.setTelephone("+261 34 11 028 15");
                e79.setPrixMoyen(new BigDecimal("225000"));
                e79.setNote(new BigDecimal("3"));
                e79.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e79.setDescription("Bienvenue à Résidence Atlantis. Situé dans le quartier de Ankadindramamy.");
                e79.setCategorie(hotel);
                e79.setGeom(geometryFactory.createPoint(new Coordinate(47.552020, -18.868011)));
                e79.getGeom().setSRID(4326);
                etablissementRepository.save(e79);

                Etablissement e80 = new Etablissement();
                e80.setNom("La Résidence d'Ankerana");
                e80.setAdresse("Ivandry");
                e80.setTelephone("+261 34 01 807 70");
                e80.setPrixMoyen(new BigDecimal("225000"));
                e80.setNote(new BigDecimal("3"));
                e80.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e80.setDescription("Bienvenue à La Résidence d'Ankerana. Situé dans le quartier de Ivandry.");
                e80.setCategorie(hotel);
                e80.setGeom(geometryFactory.createPoint(new Coordinate(47.555232, -18.887337)));
                e80.getGeom().setSRID(4326);
                etablissementRepository.save(e80);

                Etablissement e81 = new Etablissement();
                e81.setNom("Hôtel Résidence Lapasoa");
                e81.setAdresse("Isoraka");
                e81.setTelephone("+261 20 22 611 40");
                e81.setPrixMoyen(new BigDecimal("225000"));
                e81.setNote(new BigDecimal("3"));
                e81.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e81.setDescription("Bienvenue à Hôtel Résidence Lapasoa. Situé dans le quartier de Isoraka.");
                e81.setCategorie(hotel);
                e81.setGeom(geometryFactory.createPoint(new Coordinate(47.520957, -18.911718)));
                e81.getGeom().setSRID(4326);
                etablissementRepository.save(e81);

                Etablissement e82 = new Etablissement();
                e82.setNom("Delta Hotels by Marriott Antananarivo");
                e82.setAdresse("Antananarivo Centre");
                e82.setTelephone("");
                e82.setPrixMoyen(new BigDecimal("225000"));
                e82.setNote(new BigDecimal("3"));
                e82.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e82.setDescription("Bienvenue à Delta Hotels by Marriott Antananarivo. Situé dans le quartier de Antananarivo Centre.");
                e82.setCategorie(hotel);
                e82.setGeom(geometryFactory.createPoint(new Coordinate(47.521063, -18.899437)));
                e82.getGeom().setSRID(4326);
                etablissementRepository.save(e82);

                Etablissement e83 = new Etablissement();
                e83.setNom("Nosy Manga");
                e83.setAdresse("Près aéroport (Ivato)");
                e83.setTelephone("+261 38 62 975 74");
                e83.setPrixMoyen(new BigDecimal("225000"));
                e83.setNote(new BigDecimal("3"));
                e83.setPhotos(Arrays.asList("https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=500&fit=crop"));
                e83.setDescription("Bienvenue à Nosy Manga. Situé dans le quartier de Près aéroport (Ivato).");
                e83.setCategorie(hotel);
                e83.setGeom(geometryFactory.createPoint(new Coordinate(47.472547, -18.808574)));
                e83.getGeom().setSRID(4326);
                etablissementRepository.save(e83);

            }
        };
    }
}
